// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// The project ID is correct: njaiepxbftbahkpqmrip
const SUPABASE_URL = "https://njaiepxbftbahkpqmrip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYWllcHhiZnRiYWhrcHFtcmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjY0MjAsImV4cCI6MjA2MDQwMjQyMH0.e02H1X0LCZeZWHc7KPX2CLrqGxDUMp6d3B4a-QIU_Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
